#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 25 12:03:22 2021

@author: surya
"""

# import pandas as pd
# X = pd.read_csv('test.txt', sep="\t", header=None)


import csv
import numpy as np
import pandas as pd
from pandas import DataFrame
import networkx as nx
import matplotlib.pyplot as plt

fields = ['symbol1', 'symbol2']

csv_reader = pd.read_csv('PPI_IID_FINAL.txt', usecols=fields, sep="\t")

# csv_reader.to_csv(r'andas.txt', index=None, sep='\t', mode='a')

csv_reader_numpy=csv_reader.to_numpy()